import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :jamie, JamieWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Force SSL for production
config :jamie, JamieWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto], hsts: true]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
